name: Deploy to Personal GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - run: flutter build web --release

      - name: Deploy to personal GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          user_name: DrewBrandt
          user_email: DrewBrandt@users.noreply.github.com
